---
title: Sindicatos
---

Los datos cuantitativos sobre los sindicatos en Chile son producidos y concentrados por la Dirección del Trabajo, en tanto es la institución en la cuál los sindicatos deben registrar a sus socios, socias y a sus estatutos, para constituirse como tales, y registrar sus elecciones internas y sus contratos colectivos para mantener su estado de activos. Así también, la institución permanentemente monitorea la situación de las relaciones laborales en el país mediante estudios como la Encuesta Laboral (Encla). Adicionalmente, se pueden conseguir datos sobre sindicatos para los años anteriores a los noventa en base a la revisión bibliográfica y al trabajo de archivo. A continuación, se detallan cada una de las fuentes y se colocan los enlaces a los repositorios particulares en los cuáles desarrollamos cada tema.

## [Compendios y anuarios estadísticos](https://github.com/nicolasrattor/COMPENDIOS_DT)

En este [repositorio](https://github.com/nicolasrattor/COMPENDIOS_DT) hemos ordenados los datos de los Compendios y Anuarios estadísticos de la Dirección del Trabajo, dejando links para descargar directamente en formato excel cada cuadro (sin tener que lidiar con el formato pdf). Los datos oficiales se presentan depurados y a nivel nacional, rama de actividad, región, sexo y tipo de sindicato, por lo que no requieren mayor tratamiento; se publican con un retraso de aproximadamente dos o tres años (a marzo de 2021 solo se ha publicado el compendio hasta 2019) y el periodo que abarcan se limita hasta los años noventa (1990-2019). Para obtener información más allá de este periodo y/o a nivel desagregado (microdato con información de sindicatos y empresa) hemos desarrollado los otros repositorios.

## [Ventanilla sindical](https://github.com/nicolasrattor/Ventanilla_Sindicatos_DT)

Se desarrolla un código para procesar y analizar el microdato de la [Ventanilla sindical](https://github.com/nicolasrattor/Ventanilla_Sindicatos_DT) de la Dirección del Trabajo. En la página hay información de cada sindicato constituido en el país desde 1920 hasta 2020. La información no se encuentra depurada y presenta contradicciones, por lo que como repositorio la hemos depurado. La base está actualizada hasta el momento mismo en que se descarga y presenta información sobre número de socias y socios, fecha de constitución del sindicato, estado, fecha de último registro, tipo de sindicato, rut de la empresa a la que pertenece el sindicato, entre otras cuestiones. Una vez depurada la base permite obtener indicadores actualizados y alternativos a los oficiales publicados con retraso por la Dirección del Trabajo. En el repositorio ya se encuentra publicada una [Minuta](https://github.com/nicolasrattor/Ventanilla_Sindicatos_DT/raw/main/Minuta1/Minuta1.pdf) con resultados y explicaciones metodológicas. Con estos mismos datos se ha elaborado una [aplicación](https://nicolasrattor.shinyapps.io/sindicatos_empresas/) para contar sindicatos en empresas. 

## [Revisión bibliográfica](https://github.com/dpolancon/tasa_afiliacion_sindical)

En el [repositorio](https://github.com/dpolancon/tasa_afiliacion_sindical) y la [minuta](https://github.com/ObservatorioSindical/tasa_afiliacion_sindical/raw/main/afiliacion_sindical.pdf) se sistematizan diversos esfuerzos aislados que han tratado de reconstruir las tasas sindicales de largo plazo en Chile. Estos esfuerzos, tradicionalmente se han publicado como libros o documentos de trabajo. Se expone una propuesta de empalme que abarca el periodo 1932-2010. Con esto, se espera aportar a la construcción de una base sólida para su utilización en futuras investigaciones sobre el movimiento sindical nacional.

## [Encuesta laboral (1998-2019)](https://github.com/nicolasrattor/Enclas_1998_2019/)

El repositorio está en desarrollo y se espera sacar una minuta en el mediano plazo con el detalle del procesamiento y análisis de las distintas versiones de la [Encuesta Laboral (1998-2019)](https://github.com/nicolasrattor/Enclas_1998_2019/), la cuál ha sido aplicada con una frecuente de entre 2 a 5 años a una muestra aleatoria de empresas entre 1998 y 2019. Si en la empresa existe sindicato este es entrevistado. Permite tener información sobre las características de las empresas en las que se concentran los sindicatos y cuestiones relacionadas a sus estrategias, recursos de poder y orientaciones socio políticas.
